import { cn } from '@/utils/cn'
import './globals.css'
import type { Metadata } from 'next'
import { Archivo } from 'next/font/google'
import { Header } from '@/components/Layout/Header'

const arquivo = Archivo({
  subsets: ['latin'],
  display: 'swap',
  weight: ['400', '500', '700'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={cn(arquivo.className, 'bg-gray-250 flex min-h-screen flex-col px-[10px]')}>
        <Header />
        {children}
      </body>
    </html>
  )
}
